### ISSUE TITLE
Review by Team24 Brown Bears

### ISSUE THREAD

**Issue by addod19** [abruzy/react-calculator#8]
Hi @abruzy, congratulations on a great job with this amazing project :smile:
However, we found a bug, that could be fixed by improving the division algorithm, for example; dividing a number by zero '0' :+1:
Congratulations :fireworks:

**Comment by abruzy** [comment]
Thi

**Comment by abruzy** [comment]
This issue has been resolved, please play with it  and let me know if there's any bug

Thanks @addod19  for pointing out this bug :+1:
